/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.admin;

import java.util.LinkedHashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import mycom.controllers.UserController;
import mycom.models.User;
import mycom.services.ResetSystem;
import mycom.utils.WordProcessing;

/**
 *
 * @author sheaw
 */
public class AdminDashboardGUI extends javax.swing.JInternalFrame {
    User admin;
    UserController usrCtrl;
    /**
     * Creates new form AdminUserManagement
     */
    public AdminDashboardGUI(UserController usrCtrl) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null); // set the top frame thingy null
        
        this.admin = usrCtrl.getActiveUser();
        this.usrCtrl = usrCtrl;
        
        showTotalUsr();
        showAdminDetails();
    }
    
    private void showTotalUsr() {
        int totalUser, totalManager, totalStaff;
//        UserManagement usrServices = usrCtrl.getUserServices();
        totalUser = mycom.services.UserManagement.getAllUsers().size();
        totalManager = mycom.services.UserManagement.getManagers().size();
        totalStaff = mycom.services.UserManagement.getStaffs().size();
        totalUsr.setText(String.valueOf(totalUser)) ;
        totalMng.setText(String.valueOf(totalManager));
        totalStf.setText(String.valueOf(totalStaff));
    }
    
    private void showAdminDetails() {
        adminName.setText(this.admin.getName());
        adminId.setText(this.admin.getId());
        adminRole.setText(WordProcessing.capitalizeEachWord(this.admin.type));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalMngPanel = new javax.swing.JPanel();
        totalMngLabel = new javax.swing.JLabel();
        totalMng = new javax.swing.JLabel();
        totalUsrPanel = new javax.swing.JPanel();
        totalUsrLabel = new javax.swing.JLabel();
        totalUsr = new javax.swing.JLabel();
        totalStfPanel = new javax.swing.JPanel();
        totalStfLabel = new javax.swing.JLabel();
        totalStf = new javax.swing.JLabel();
        adminCredentialsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adminName = new javax.swing.JTextField();
        separator1 = new javax.swing.JLabel();
        separator2 = new javax.swing.JLabel();
        adminId = new javax.swing.JTextField();
        separator3 = new javax.swing.JLabel();
        adminRole = new javax.swing.JTextField();
        changeNameButton = new javax.swing.JButton();
        changePwdButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resetInventoryQuickButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        addUserQuickButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        resetSystemQuickButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(770, 642));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 642));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quick Actions");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        totalMngPanel.setBackground(new java.awt.Color(211, 229, 246));
        totalMngPanel.setPreferredSize(new java.awt.Dimension(250, 176));

        totalMngLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalMngLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMngLabel.setText("Total Manager");
        totalMngLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalMng.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalMng.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMng.setText("3");
        totalMng.setAlignmentY(1.0F);
        totalMng.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout totalMngPanelLayout = new javax.swing.GroupLayout(totalMngPanel);
        totalMngPanel.setLayout(totalMngPanelLayout);
        totalMngPanelLayout.setHorizontalGroup(
            totalMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalMngLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(totalMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalMngPanelLayout.setVerticalGroup(
            totalMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalMngPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(totalMngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalMng, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(totalMngPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 150));

        totalUsrPanel.setBackground(new java.awt.Color(211, 229, 246));
        totalUsrPanel.setPreferredSize(new java.awt.Dimension(250, 176));

        totalUsrLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalUsrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUsrLabel.setText("Total User");

        totalUsr.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUsr.setText("3");
        totalUsr.setAlignmentY(1.0F);

        javax.swing.GroupLayout totalUsrPanelLayout = new javax.swing.GroupLayout(totalUsrPanel);
        totalUsrPanel.setLayout(totalUsrPanelLayout);
        totalUsrPanelLayout.setHorizontalGroup(
            totalUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalUsrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(totalUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalUsrPanelLayout.setVerticalGroup(
            totalUsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalUsrPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(totalUsrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(totalUsrPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 150));

        totalStfPanel.setBackground(new java.awt.Color(211, 229, 246));
        totalStfPanel.setPreferredSize(new java.awt.Dimension(510, 188));

        totalStfLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalStfLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalStfLabel.setText("Total Warehouse Staff");
        totalStfLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalStf.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalStf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalStf.setText("10");
        totalStf.setAlignmentY(1.0F);

        javax.swing.GroupLayout totalStfPanelLayout = new javax.swing.GroupLayout(totalStfPanel);
        totalStfPanel.setLayout(totalStfPanelLayout);
        totalStfPanelLayout.setHorizontalGroup(
            totalStfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalStfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(totalStf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalStfPanelLayout.setVerticalGroup(
            totalStfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalStfPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(totalStfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalStf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(totalStfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 370, 150));

        adminCredentialsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        adminCredentialsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Admin Name");
        jLabel4.setAlignmentY(1.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Admin ID");
        jLabel5.setAlignmentY(1.0F);
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setText("Role");
        jLabel6.setAlignmentY(1.0F);
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User Details");

        adminName.setEditable(false);
        adminName.setBackground(java.awt.SystemColor.controlHighlight);
        adminName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminName.setText("hahaha");
        adminName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        separator1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator1.setText(":");

        separator2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator2.setText(":");

        adminId.setEditable(false);
        adminId.setBackground(java.awt.SystemColor.controlHighlight);
        adminId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminId.setText("#SADM001");
        adminId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        separator3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator3.setText(":");

        adminRole.setEditable(false);
        adminRole.setBackground(java.awt.SystemColor.controlHighlight);
        adminRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminRole.setText("Super Admin");
        adminRole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        changeNameButton.setText("Change Name");
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        changePwdButton.setText("Change Password");
        changePwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminCredentialsPanelLayout = new javax.swing.GroupLayout(adminCredentialsPanel);
        adminCredentialsPanel.setLayout(adminCredentialsPanelLayout);
        adminCredentialsPanelLayout.setHorizontalGroup(
            adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                        .addComponent(changeNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePwdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                        .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminName))
                            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)
                                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adminId)
                                        .addGap(11, 11, 11))
                                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                        .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adminRole, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))))
                        .addGap(12, 12, 12))))
        );
        adminCredentialsPanelLayout.setVerticalGroup(
            adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator1))
                .addGap(26, 26, 26)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adminId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator2))
                .addGap(32, 32, 32)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator3))
                .addGap(18, 18, 18)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePwdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jPanel1.add(adminCredentialsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 310, 320));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        resetInventoryQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        resetInventoryQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetInventoryQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetInventoryQuickButtonMouseClicked(evt);
            }
        });
        resetInventoryQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset Inventory");
        resetInventoryQuickButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 190, 100));

        jPanel1.add(resetInventoryQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 200, 100));

        addUserQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        addUserQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUserQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserQuickButtonMouseClicked(evt);
            }
        });
        addUserQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add User");
        addUserQuickButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 190, 100));

        jPanel1.add(addUserQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 200, 100));

        resetSystemQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        resetSystemQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetSystemQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetSystemQuickButtonMouseClicked(evt);
            }
        });
        resetSystemQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reset System");
        resetSystemQuickButton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 190, 100));

        jPanel1.add(resetSystemQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 200, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserQuickButtonMouseClicked
        String[] roles = {"Staff", "Manager"};
        JComboBox<String> roleCombo = new JComboBox<>(roles);
    
        JTextField field1 = new JTextField();

        Object[] message = {
            "User Name:", field1,
            "User Role", roleCombo
        };

        int option = JOptionPane.showConfirmDialog(this, message, "Create New User", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            String tempUserPwd = mycom.services.UserManagement.generateTemporaryPassword();
            String usrName = field1.getText();
            String usrRole = roleCombo.getSelectedItem().toString().toLowerCase();
            LinkedHashMap<String, String> msg = this.usrCtrl.createUser(usrName, tempUserPwd, usrRole);
            User newUsr = mycom.services.UserManagement.getUserById(msg.get("newUserId"));
            if (newUsr != null) {
                JOptionPane.showMessageDialog(this, String.format("New User ('%s', '%s') is created!", newUsr.getId(), newUsr.getName()));
                String newUsrPwd = newUsr.getPwd();
                String showNewUsr = String.format("User ID: %s\nUser Password: %s\n\nPlease notfy the user to update the password for security", newUsr.getId(), newUsr.getPwd());
                JOptionPane.showMessageDialog(this, showNewUsr, "New User Credentials", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, String.format("Fail to create new User '%s' :(\n", usrName) + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addUserQuickButtonMouseClicked

    private void resetSystemQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetSystemQuickButtonMouseClicked
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to reset the system?\nThis action cannot be undone!",
            "Confirm System Reset",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
            );

        if (choice == JOptionPane.YES_OPTION) {
            if (ResetSystem.resetSystem(this.usrCtrl.getActiveUser()).get("success") != null) {
                JOptionPane.showMessageDialog(this, "System has been reset successfully!", "Reset Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to reset system :(", "Reset Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "System reset canceled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_resetSystemQuickButtonMouseClicked

    private void resetInventoryQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetInventoryQuickButtonMouseClicked
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to reset the inventory?\nThis action cannot be undone!",
            "Confirm Inventory Reset",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
            );

        if (choice == JOptionPane.YES_OPTION) {
            LinkedHashMap<String, String> msg = this.usrCtrl.getPPEController().resetInventory();
            if (msg.get("success") != null) {
                JOptionPane.showMessageDialog(this, "Inventory has been reset successfully!", "Reset Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to reset inventory :(\n" + msg.get("msg"), "Reset Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Inventory reset canceled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_resetInventoryQuickButtonMouseClicked

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        String newName = JOptionPane.showInputDialog(this, "New Name", "Modify Admin Name", JOptionPane.QUESTION_MESSAGE);
        
        if (newName != null) {
            LinkedHashMap<String, String> msg = this.usrCtrl.modifyAdminName(newName);
            if (msg.get("success") != null) {
                JOptionPane.showMessageDialog(this, "Super Admin name is updated!");
                User updatedAdmin = mycom.services.UserManagement.getSuperAdmin();
                this.usrCtrl = new UserController();
                this.usrCtrl.updateActiveUser(updatedAdmin);
                this.admin = this.usrCtrl.getActiveUser();
                System.out.println(this.admin);
                adminName.setText(this.admin.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Super Admin name update failed :(\n" + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
                System.out.println("User canceled input.");
        }
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void changePwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdButtonActionPerformed
        JPasswordField newPwd = new JPasswordField();
        JPasswordField confirmPwd = new JPasswordField();

        Object[] message = {
            "New Password:", newPwd,
            "Confirm Password:", confirmPwd
        };
        int option = JOptionPane.showConfirmDialog(this, message, "Modify Admin Paassword", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            String newPassword = newPwd.getText();
            String confirmPassword = confirmPwd.getText();
            if (newPassword.equals(confirmPassword)) {
                LinkedHashMap<String, String> msg = this.usrCtrl.modifyAdminPwd(newPassword);
                if (msg.get("success") != null) {
                    JOptionPane.showMessageDialog(this, "Super Admin password is updated!");
                    User updatedAdmin = mycom.services.UserManagement.getSuperAdmin();
                    this.usrCtrl = new UserController();
                    this.usrCtrl.updateActiveUser(updatedAdmin);
                    this.admin = this.usrCtrl.getActiveUser();
                    adminName.setText(this.admin.getName());
                } else {
                    JOptionPane.showMessageDialog(this, "Super Admin password update failed :(\n" + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
                } 
            } else {
                JOptionPane.showMessageDialog(this, "New password incorrect :(", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
                System.out.println("User canceled input.");
        }
    }//GEN-LAST:event_changePwdButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addUserQuickButton;
    private javax.swing.JPanel adminCredentialsPanel;
    private javax.swing.JTextField adminId;
    private javax.swing.JTextField adminName;
    private javax.swing.JTextField adminRole;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton changePwdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel resetInventoryQuickButton;
    private javax.swing.JPanel resetSystemQuickButton;
    private javax.swing.JLabel separator1;
    private javax.swing.JLabel separator2;
    private javax.swing.JLabel separator3;
    private javax.swing.JLabel totalMng;
    private javax.swing.JLabel totalMngLabel;
    private javax.swing.JPanel totalMngPanel;
    private javax.swing.JLabel totalStf;
    private javax.swing.JLabel totalStfLabel;
    private javax.swing.JPanel totalStfPanel;
    private javax.swing.JLabel totalUsr;
    private javax.swing.JLabel totalUsrLabel;
    private javax.swing.JPanel totalUsrPanel;
    // End of variables declaration//GEN-END:variables
}
