/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.admin;

import mycom.controllers.UserController;
import mycom.gui.LoginGUI;
import mycom.models.User;

/**
 *
 * @author sheaw
 */
public class AdminNavigation extends javax.swing.JFrame {
    User admin;
    UserController usrCtrl;
    /**
     * Creates new form AdminDashboard
     */
    public AdminNavigation(UserController usrCtrl) {
        initComponents();
        this.admin = usrCtrl.getActiveUser();
        this.usrCtrl = usrCtrl;
        
        AdminDashboardGUI dashboard = new AdminDashboardGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        welcomeAdminText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        adminLogoutButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbacButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        adminSystemManagementButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adminUserManagementButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        adminDashboardButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1120, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 730));

        topBar.setBackground(new java.awt.Color(144, 174, 223));
        topBar.setPreferredSize(new java.awt.Dimension(1120, 88));
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/icon.png"))); // NOI18N
        jLabel1.setText("PPE Inventory Management System");
        jLabel1.setIconTextGap(40);
        topBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        sideBar.setBackground(new java.awt.Color(52, 52, 58));
        sideBar.setPreferredSize(new java.awt.Dimension(350, 642));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeAdminText.setBorder(null);
        welcomeAdminText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        welcomeAdminText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(52, 52, 58));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome, \nAdmin");
        jTextArea1.setWrapStyleWord(true);
        welcomeAdminText.setViewportView(jTextArea1);

        sideBar.add(welcomeAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/welcome_image.png"))); // NOI18N
        sideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 350, 250));

        adminLogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminLogoutButton.setPreferredSize(new java.awt.Dimension(350, 50));
        adminLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLogoutButtonMouseClicked(evt);
            }
        });
        adminLogoutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Logout");
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminLogoutButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 350, -1));

        sideBar.add(adminLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 350, 50));

        rbacButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbacButton.setPreferredSize(new java.awt.Dimension(350, 50));
        rbacButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbacButtonMouseClicked(evt);
            }
        });
        rbacButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Role-Based Access Control");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbacButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 350, -1));

        sideBar.add(rbacButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 350, 50));

        adminSystemManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminSystemManagementButton.setPreferredSize(new java.awt.Dimension(350, 50));
        adminSystemManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminSystemManagementButtonMouseClicked(evt);
            }
        });
        adminSystemManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("System Management");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminSystemManagementButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 350, -1));

        sideBar.add(adminSystemManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 350, 50));

        adminUserManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminUserManagementButton.setPreferredSize(new java.awt.Dimension(350, 50));
        adminUserManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUserManagementButtonMouseClicked(evt);
            }
        });
        adminUserManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Management");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminUserManagementButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 350, -1));

        sideBar.add(adminUserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, 50));

        adminDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminDashboardButton.setPreferredSize(new java.awt.Dimension(350, 50));
        adminDashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminDashboardButtonMouseClicked(evt);
            }
        });
        adminDashboardButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminDashboardButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 350, -1));

        sideBar.add(adminDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 50));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(770, 642));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminDashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDashboardButtonMouseClicked
        AdminDashboardGUI dashboard = new AdminDashboardGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
    }//GEN-LAST:event_adminDashboardButtonMouseClicked

    private void adminUserManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUserManagementButtonMouseClicked
        UserManagementGUI usrManagement = new UserManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(usrManagement).setVisible(true);
    }//GEN-LAST:event_adminUserManagementButtonMouseClicked

    private void adminSystemManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSystemManagementButtonMouseClicked
        SystemManagementGUI systemManagement = new SystemManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(systemManagement).setVisible(true);
    }//GEN-LAST:event_adminSystemManagementButtonMouseClicked

    private void rbacButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbacButtonMouseClicked
        AdminRBACGUI adminRbac = new AdminRBACGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(adminRbac).setVisible(true);
    }//GEN-LAST:event_rbacButtonMouseClicked

    private void adminLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLogoutButtonMouseClicked
        dispose();
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.usrCtrl.userLogout(this.admin);
    }//GEN-LAST:event_adminLogoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminNavigation().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminDashboardButton;
    private javax.swing.JPanel adminLogoutButton;
    private javax.swing.JPanel adminSystemManagementButton;
    private javax.swing.JPanel adminUserManagementButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel rbacButton;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel topBar;
    private javax.swing.JScrollPane welcomeAdminText;
    // End of variables declaration//GEN-END:variables
}
