/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.staff;

import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import mycom.gui.Manager.*;
import mycom.gui.Admin.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import mycom.config.SystemConfig;
import mycom.controllers.UserController;
import mycom.models.PPEItem;
import mycom.models.User;
import mycom.services.HospitalManagement;
import mycom.services.PPEManagement;
import mycom.services.SupplierManagement;
import mycom.services.UserManagement;
import mycom.utils.WordProcessing;

/**
 *
 * @author sheaw
 */
public class StaffDashboard extends javax.swing.JInternalFrame {
    UserController usrCtrl;
    User staff;
    /**
     * Creates new form AdminUserManagement
     */
    public StaffDashboard(UserController usrCtrl) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null); // set the top frame thingy null
        
        this.usrCtrl = usrCtrl;
        this.staff = usrCtrl.getActiveUser();
        if (this.usrCtrl.getActiveUser().type.equalsIgnoreCase("super admin")) {
            this.usrCtrl.updateActiveUser(UserManagement.getSuperAdmin());
        } else {
            this.usrCtrl.updateActiveUser(UserManagement.getUserById(this.usrCtrl.getActiveUser().getId()));
        }
        showDashboardDetails();
        showStaffDetails();
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            protected void done() {
                lowStockAlert();
            }
        }.execute();

        if (this.usrCtrl.getUserServices().getInitializeInventory()) {
            initializeInventoryQuickButton.setVisible(true);
            initializeInventoryQuickButton.setEnabled(true);
        } else {
            initializeInventoryQuickButton.setVisible(false);
            initializeInventoryQuickButton.setEnabled(false);
        }
        
        if (this.usrCtrl.getUserServices().getResetInventory()) {
            resetInventoryQuickButton.setVisible(true);
            resetInventoryQuickButton.setEnabled(true);
        } else {
            resetInventoryQuickButton.setVisible(false);
            resetInventoryQuickButton.setEnabled(false);
        }
    }
    
    private void lowStockAlert() {
        if (PPEManagement.getLowStockItems().size() > 0) {
            String msg = String.valueOf(PPEManagement.getLowStockItems().size()) + " PPE items are below the threshold quantity of " + String.valueOf(SystemConfig.thresholdQuantity) + " boxes!";
            JOptionPane.showMessageDialog(this, msg, "LOW STOCK ALERT",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void showDashboardDetails() {
        int totalSupplier, totalHospital, totalItems, totalLowStockItems;
//        UserManagement usrServices = usrCtrl.getUserServices();
        totalSupplier = SupplierManagement.getAllSuppliers().size();
        totalHospital = HospitalManagement.getAllHospitals().size();
        totalItems = this.usrCtrl.getPPEController().getTotalInventoryItems();
        totalLowStockItems = this.usrCtrl.getPPEController().lowStockAlert().size();
        totalSuppliers.setText(String.valueOf(totalSupplier));
        totalHospitals.setText(String.valueOf(totalHospital));
        totalInventories.setText(String.valueOf(totalItems));
        totalLowStocks.setText(String.valueOf(totalLowStockItems));
    }
    
    private void showStaffDetails() {
        staffName.setText(this.staff.getName());
        staffId.setText(this.staff.getId());
        staffRole.setText(WordProcessing.capitalizeEachWord(this.staff.type));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalHospitalPanel = new javax.swing.JPanel();
        totalMngLabel = new javax.swing.JLabel();
        totalHospitals = new javax.swing.JLabel();
        totalSupplierPanel = new javax.swing.JPanel();
        totalUsrLabel = new javax.swing.JLabel();
        totalSuppliers = new javax.swing.JLabel();
        totalInventory1 = new javax.swing.JPanel();
        lowStockLabel = new javax.swing.JLabel();
        totalLowStocks = new javax.swing.JLabel();
        itemUnit1 = new javax.swing.JLabel();
        totalInventory = new javax.swing.JPanel();
        totalInventoriesLabel = new javax.swing.JLabel();
        totalInventories = new javax.swing.JLabel();
        itemUnit = new javax.swing.JLabel();
        adminCredentialsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        staffName = new javax.swing.JTextField();
        separator1 = new javax.swing.JLabel();
        separator2 = new javax.swing.JLabel();
        staffId = new javax.swing.JTextField();
        separator3 = new javax.swing.JLabel();
        staffRole = new javax.swing.JTextField();
        changeNameButton = new javax.swing.JButton();
        changePwdButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resetInventoryQuickButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        addItemQuickButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lowStockQuickButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        initializeInventoryQuickButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(770, 642));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 642));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quick Actions");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        totalHospitalPanel.setBackground(new java.awt.Color(211, 229, 246));
        totalHospitalPanel.setPreferredSize(new java.awt.Dimension(250, 176));

        totalMngLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalMngLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMngLabel.setText("Total Hospital");
        totalMngLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalHospitals.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalHospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalHospitals.setText("3");
        totalHospitals.setAlignmentY(1.0F);
        totalHospitals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout totalHospitalPanelLayout = new javax.swing.GroupLayout(totalHospitalPanel);
        totalHospitalPanel.setLayout(totalHospitalPanelLayout);
        totalHospitalPanelLayout.setHorizontalGroup(
            totalHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalMngLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(totalHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalHospitalPanelLayout.setVerticalGroup(
            totalHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalHospitalPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(totalMngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(totalHospitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 150));

        totalSupplierPanel.setBackground(new java.awt.Color(211, 229, 246));
        totalSupplierPanel.setPreferredSize(new java.awt.Dimension(250, 176));

        totalUsrLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalUsrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUsrLabel.setText("Total Supplier");

        totalSuppliers.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalSuppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSuppliers.setText("3");
        totalSuppliers.setAlignmentY(1.0F);

        javax.swing.GroupLayout totalSupplierPanelLayout = new javax.swing.GroupLayout(totalSupplierPanel);
        totalSupplierPanel.setLayout(totalSupplierPanelLayout);
        totalSupplierPanelLayout.setHorizontalGroup(
            totalSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalUsrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(totalSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalSupplierPanelLayout.setVerticalGroup(
            totalSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalSupplierPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(totalUsrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(totalSupplierPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 150));

        totalInventory1.setBackground(new java.awt.Color(211, 229, 246));
        totalInventory1.setPreferredSize(new java.awt.Dimension(510, 188));

        lowStockLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lowStockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowStockLabel.setText("Low Stock Items");
        lowStockLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalLowStocks.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalLowStocks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLowStocks.setText("10");
        totalLowStocks.setAlignmentY(1.0F);

        itemUnit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemUnit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemUnit1.setText("items");
        itemUnit1.setAlignmentY(1.0F);
        itemUnit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout totalInventory1Layout = new javax.swing.GroupLayout(totalInventory1);
        totalInventory1.setLayout(totalInventory1Layout);
        totalInventory1Layout.setHorizontalGroup(
            totalInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalInventory1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(totalInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lowStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(totalInventory1Layout.createSequentialGroup()
                        .addComponent(totalLowStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemUnit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(202, 202, 202))
        );
        totalInventory1Layout.setVerticalGroup(
            totalInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalInventory1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lowStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(totalInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLowStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(totalInventory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, 150));

        totalInventory.setBackground(new java.awt.Color(211, 229, 246));
        totalInventory.setPreferredSize(new java.awt.Dimension(510, 188));

        totalInventoriesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalInventoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalInventoriesLabel.setText("Total Inventory");
        totalInventoriesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalInventories.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalInventories.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalInventories.setText("10");
        totalInventories.setAlignmentY(1.0F);

        itemUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemUnit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemUnit.setText("items");
        itemUnit.setAlignmentY(1.0F);
        itemUnit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout totalInventoryLayout = new javax.swing.GroupLayout(totalInventory);
        totalInventory.setLayout(totalInventoryLayout);
        totalInventoryLayout.setHorizontalGroup(
            totalInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(totalInventoryLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(totalInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalInventoriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(totalInventoryLayout.createSequentialGroup()
                        .addComponent(totalInventories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(202, 202, 202))
        );
        totalInventoryLayout.setVerticalGroup(
            totalInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalInventoryLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(totalInventoriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(totalInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalInventories, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(totalInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, 150));

        adminCredentialsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        adminCredentialsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Staff Name");
        jLabel4.setAlignmentY(1.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Staff ID");
        jLabel5.setAlignmentY(1.0F);
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setText("Role");
        jLabel6.setAlignmentY(1.0F);
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User Details");

        staffName.setEditable(false);
        staffName.setBackground(java.awt.SystemColor.controlHighlight);
        staffName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staffName.setText("hahaha");
        staffName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        separator1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator1.setText(":");

        separator2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator2.setText(":");

        staffId.setEditable(false);
        staffId.setBackground(java.awt.SystemColor.controlHighlight);
        staffId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staffId.setText("#STF00001");
        staffId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        separator3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        separator3.setText(":");

        staffRole.setEditable(false);
        staffRole.setBackground(java.awt.SystemColor.controlHighlight);
        staffRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staffRole.setText("Staff");
        staffRole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        staffRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRoleActionPerformed(evt);
            }
        });

        changeNameButton.setText("Change Name");
        changeNameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        changePwdButton.setText("Change Password");
        changePwdButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminCredentialsPanelLayout = new javax.swing.GroupLayout(adminCredentialsPanel);
        adminCredentialsPanel.setLayout(adminCredentialsPanelLayout);
        adminCredentialsPanelLayout.setHorizontalGroup(
            adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                        .addComponent(changeNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePwdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                        .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffName))
                            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)
                                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(staffId)
                                        .addGap(11, 11, 11))
                                    .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                                        .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(staffRole, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                        .addGap(12, 12, 12))))
        );
        adminCredentialsPanelLayout.setVerticalGroup(
            adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCredentialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator1))
                .addGap(26, 26, 26)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(staffId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator2))
                .addGap(32, 32, 32)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(staffRole, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separator3))
                .addGap(18, 18, 18)
                .addGroup(adminCredentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePwdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jPanel1.add(adminCredentialsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 310, 320));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        resetInventoryQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        resetInventoryQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetInventoryQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetInventoryQuickButtonMouseClicked(evt);
            }
        });
        resetInventoryQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset Inventory");
        resetInventoryQuickButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 150, 100));

        jPanel1.add(resetInventoryQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 160, 100));

        addItemQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        addItemQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addItemQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemQuickButtonMouseClicked(evt);
            }
        });
        addItemQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Item");
        addItemQuickButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 150, 100));

        jPanel1.add(addItemQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 160, 100));

        lowStockQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        lowStockQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lowStockQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Low Stock Items");
        lowStockQuickButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 150, 100));

        jPanel1.add(lowStockQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 160, 100));

        initializeInventoryQuickButton.setBackground(new java.awt.Color(153, 182, 226));
        initializeInventoryQuickButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        initializeInventoryQuickButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                initializeInventoryQuickButtonMouseClicked(evt);
            }
        });
        initializeInventoryQuickButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Initialize Inventory");
        initializeInventoryQuickButton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 150, 100));

        jPanel1.add(initializeInventoryQuickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 160, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffRoleActionPerformed

    private void initializeInventoryQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initializeInventoryQuickButtonMouseClicked
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to initialize the inventory?\nThis action cannot be undone!",
            "Confirm Inventory Initialization",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
            );

        if (choice == JOptionPane.YES_OPTION) {
            LinkedHashMap<String, String> msg = this.usrCtrl.getPPEController().initializeInventory();
            if (msg.get("success") != null) {
                JOptionPane.showMessageDialog(this, "Inventory has been initialized successfully!", "Reset Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to initialize inventory :(\n" + msg.get("msg"), "Reset Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Inventory initialization canceled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_initializeInventoryQuickButtonMouseClicked

    private void resetInventoryQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetInventoryQuickButtonMouseClicked
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to reset the inventory?\nThis action cannot be undone!",
            "Confirm Inventory Reset",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
            );

        if (choice == JOptionPane.YES_OPTION) {
            LinkedHashMap<String, String> msg = this.usrCtrl.getPPEController().resetInventory();
            if (msg.get("success") != null) {
                JOptionPane.showMessageDialog(this, "Inventory has been reset successfully!", "Reset Complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to reset inventory :(\n" + msg.get("msg"), "Reset Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Inventory reset canceled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_resetInventoryQuickButtonMouseClicked

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        String newName = JOptionPane.showInputDialog(this, "New Name", "Modify Staff Name", JOptionPane.QUESTION_MESSAGE);
        
        if (newName != null) {
            LinkedHashMap<String, String> msg = this.usrCtrl.modifyUserName(newName, this.staff.getId());
            if (msg.get("success") != null) {
                JOptionPane.showMessageDialog(this, "Staff name is updated!");
                User updatedStaff = mycom.services.UserManagement.getUserById(this.staff.getId());
                this.usrCtrl = new UserController();
                this.usrCtrl.updateActiveUser(updatedStaff);
                this.staff = this.usrCtrl.getActiveUser();
                staffName.setText(this.staff.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Staff name update failed :(\n" + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
                System.out.println("User canceled input.");
        }
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void changePwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdButtonActionPerformed
        JPasswordField newPwd = new JPasswordField();
        JPasswordField confirmPwd = new JPasswordField();

        Object[] message = {
            "New Password:", newPwd,
            "Confirm Password:", confirmPwd
        };
        int option = JOptionPane.showConfirmDialog(this, message, "Modify Staff Paassword", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            String newPassword = newPwd.getText();
            String confirmPassword = confirmPwd.getText();
            if (newPassword.equals(confirmPassword)) {
                LinkedHashMap<String, String> msg = this.usrCtrl.modifyPwd(newPassword, this.staff.getId());
                if (msg.get("success") != null) {
                    JOptionPane.showMessageDialog(this, "Staff password is updated!");
                    User updatedStaff = mycom.services.UserManagement.getUserById(this.usrCtrl.getActiveUser().getId());
                    this.usrCtrl = new UserController();
                    this.usrCtrl.updateActiveUser(updatedStaff);
                    this.staff = this.usrCtrl.getActiveUser();
                    staffName.setText(this.staff.getName());
                } else {
                    JOptionPane.showMessageDialog(this, "Staff password update failed :(\n" + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
                } 
            } else {
                JOptionPane.showMessageDialog(this, "New password incorrect :(", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
                System.out.println("User canceled input.");
        }
    }//GEN-LAST:event_changePwdButtonActionPerformed

    private void addItemQuickButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemQuickButtonMouseClicked
        JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();

        Object[] message = {
            "PPE Item Code:", field1,
            "PPE Item Name:", field2
        };

        int option = JOptionPane.showConfirmDialog(this, message, "Add New PPE Items", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            String itemCode = field1.getText();
            String itemName = field2.getText();
            LinkedHashMap<String, String> msg = this.usrCtrl.getPPEController().addPPEItems(itemCode, itemName, "", 0);
            if (msg.get("success") != null) {
                PPEItem item = PPEManagement.getPPEItemByCode(msg.get("newItemCode"));
                JOptionPane.showMessageDialog(this, String.format("New PPE Item ('%s', '%s') is added!", item.getCode(), item.getName()));
            } else {
                JOptionPane.showMessageDialog(this, String.format("Fail to add new PPE Item {'%s' - '%s'} :(\n", itemCode, itemName) + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("User canceled input.");
        }
    }//GEN-LAST:event_addItemQuickButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addItemQuickButton;
    private javax.swing.JPanel adminCredentialsPanel;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton changePwdButton;
    private javax.swing.JPanel initializeInventoryQuickButton;
    private javax.swing.JLabel itemUnit;
    private javax.swing.JLabel itemUnit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JPanel lowStockQuickButton;
    private javax.swing.JPanel resetInventoryQuickButton;
    private javax.swing.JLabel separator1;
    private javax.swing.JLabel separator2;
    private javax.swing.JLabel separator3;
    private javax.swing.JTextField staffId;
    private javax.swing.JTextField staffName;
    private javax.swing.JTextField staffRole;
    private javax.swing.JPanel totalHospitalPanel;
    private javax.swing.JLabel totalHospitals;
    private javax.swing.JLabel totalInventories;
    private javax.swing.JLabel totalInventoriesLabel;
    private javax.swing.JPanel totalInventory;
    private javax.swing.JPanel totalInventory1;
    private javax.swing.JLabel totalLowStocks;
    private javax.swing.JLabel totalMngLabel;
    private javax.swing.JPanel totalSupplierPanel;
    private javax.swing.JLabel totalSuppliers;
    private javax.swing.JLabel totalUsrLabel;
    // End of variables declaration//GEN-END:variables
}
