/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.staff;

import mycom.controllers.UserController;
import mycom.gui.LoginGUI;
import mycom.gui.manager.*;
import mycom.gui.admin.*;
import mycom.models.User;
import mycom.services.UserManagement;

/**
 *
 * @author sheaw
 */
public class StaffNavigation extends javax.swing.JFrame {
    UserController usrCtrl;
    User staff;
    /**
     * Creates new form AdminDashboard
     */
    public StaffNavigation(UserController usrCtrl) {
        initComponents();
        this.usrCtrl = usrCtrl;
        this.staff = this.usrCtrl.getActiveUser();
        if (this.usrCtrl.getActiveUser().type.equalsIgnoreCase("super admin")) {
            this.usrCtrl.updateActiveUser(UserManagement.getSuperAdmin());
        } else {
            this.usrCtrl.updateActiveUser(UserManagement.getUserById(this.usrCtrl.getActiveUser().getId()));
        }
        StaffDashboard dashboard = new StaffDashboard(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
        
        if (this.usrCtrl.getUserServices().getCRUDManager() || this.usrCtrl.getUserServices().getCRUDStaff()) {
            staffUserManagementButton.setVisible(true);
            staffUserManagementButton.setEnabled(true);
        } else {
            staffUserManagementButton.setVisible(false);
            staffUserManagementButton.setEnabled(false);
        }
        if (this.usrCtrl.getUserServices().getInitializeInventory() || this.usrCtrl.getUserServices().getResetInventory() || this.usrCtrl.getUserServices().getResetSystem()) {
            staffSystemManagementButton.setVisible(true);
            staffSystemManagementButton.setEnabled(true);
        } else {
            staffSystemManagementButton.setVisible(false);
            staffSystemManagementButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        welcomeManagerText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        staffUserManagementButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        staffLowStockRecordsButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        staffSystemManagementButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        staffInventoryManagementButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        staffEntityManagementButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        staffLogoutButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        staffDashboardButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1120, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 730));

        topBar.setBackground(new java.awt.Color(144, 174, 223));
        topBar.setPreferredSize(new java.awt.Dimension(1120, 88));
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/icon.png"))); // NOI18N
        jLabel1.setText("PPE Inventory Management System");
        jLabel1.setIconTextGap(40);
        topBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        sideBar.setBackground(new java.awt.Color(52, 52, 58));
        sideBar.setPreferredSize(new java.awt.Dimension(350, 642));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeManagerText.setBorder(null);
        welcomeManagerText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        welcomeManagerText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(52, 52, 58));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome, \nStaff");
        jTextArea1.setWrapStyleWord(true);
        welcomeManagerText.setViewportView(jTextArea1);

        sideBar.add(welcomeManagerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/welcome_staff.png"))); // NOI18N
        sideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -1, 330, 250));

        staffUserManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffUserManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffUserManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffUserManagementButtonMouseClicked(evt);
            }
        });
        staffUserManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User Management");
        jLabel8.setFocusable(false);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffUserManagementButton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffUserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 350, 40));

        staffLowStockRecordsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffLowStockRecordsButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffLowStockRecordsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffLowStockRecordsButtonMouseClicked(evt);
            }
        });
        staffLowStockRecordsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Low Stock Records");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffLowStockRecordsButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffLowStockRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 350, 40));

        staffSystemManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffSystemManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffSystemManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffSystemManagementButtonMouseClicked(evt);
            }
        });
        staffSystemManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("System Management");
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffSystemManagementButton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffSystemManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 350, 40));

        staffInventoryManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffInventoryManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffInventoryManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffInventoryManagementButtonMouseClicked(evt);
            }
        });
        staffInventoryManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inventory Management");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffInventoryManagementButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffInventoryManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 350, 40));

        staffEntityManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffEntityManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffEntityManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffEntityManagementButtonMouseClicked(evt);
            }
        });
        staffEntityManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Entity Management");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffEntityManagementButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffEntityManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 350, 40));

        staffLogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffLogoutButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffLogoutButtonMouseClicked(evt);
            }
        });
        staffLogoutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Logout");
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffLogoutButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 350, 40));

        staffDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffDashboardButton.setPreferredSize(new java.awt.Dimension(350, 40));
        staffDashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffDashboardButtonMouseClicked(evt);
            }
        });
        staffDashboardButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffDashboardButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(staffDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 40));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(770, 642));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void staffDashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffDashboardButtonMouseClicked
        StaffDashboard dashboard = new StaffDashboard(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
    }//GEN-LAST:event_staffDashboardButtonMouseClicked

    private void staffEntityManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffEntityManagementButtonMouseClicked
        StaffEntityManagement entityManagement = new StaffEntityManagement(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(entityManagement).setVisible(true);
    }//GEN-LAST:event_staffEntityManagementButtonMouseClicked

    private void staffInventoryManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffInventoryManagementButtonMouseClicked
        StaffInventoryManagement inventoryManagement = new StaffInventoryManagement(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(inventoryManagement).setVisible(true);
    }//GEN-LAST:event_staffInventoryManagementButtonMouseClicked

    private void staffLowStockRecordsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLowStockRecordsButtonMouseClicked
        LowStockRecords lowStockRecords = new LowStockRecords(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(lowStockRecords).setVisible(true);
    }//GEN-LAST:event_staffLowStockRecordsButtonMouseClicked

    private void staffUserManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffUserManagementButtonMouseClicked
        UserManagementGUI userManagement = new UserManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(userManagement).setVisible(true);
    }//GEN-LAST:event_staffUserManagementButtonMouseClicked

    private void staffSystemManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffSystemManagementButtonMouseClicked
        SystemManagementGUI systemManagement = new SystemManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(systemManagement).setVisible(true);
    }//GEN-LAST:event_staffSystemManagementButtonMouseClicked

    private void staffLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLogoutButtonMouseClicked
        dispose();
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.usrCtrl.userLogout(this.staff);
    }//GEN-LAST:event_staffLogoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StaffNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StaffNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StaffNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StaffNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StaffNavigation().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel staffDashboardButton;
    private javax.swing.JPanel staffEntityManagementButton;
    private javax.swing.JPanel staffInventoryManagementButton;
    private javax.swing.JPanel staffLogoutButton;
    private javax.swing.JPanel staffLowStockRecordsButton;
    private javax.swing.JPanel staffSystemManagementButton;
    private javax.swing.JPanel staffUserManagementButton;
    private javax.swing.JPanel topBar;
    private javax.swing.JScrollPane welcomeManagerText;
    // End of variables declaration//GEN-END:variables
}
