/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.manager;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mycom.gui.Admin.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import mycom.controllers.UserController;
import mycom.models.PPEItem;
import mycom.models.User;
import mycom.services.PPEManagement;
import mycom.services.UserManagement;

/**
 *
 * @author sheaw
 */
public class LowStockRecords extends javax.swing.JInternalFrame {
    User activeUser;
    UserController usrCtrl;
    /**
     * Creates new form AdminUserManagement
     */
    public LowStockRecords(UserController usrCtrl) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null); // set the top frame thingy null
        
        this.usrCtrl = usrCtrl;
        this.activeUser = this.usrCtrl.getActiveUser();
        if (this.usrCtrl.getActiveUser().type.equalsIgnoreCase("super admin")) {
            this.usrCtrl.updateActiveUser(UserManagement.getSuperAdmin());
        } else {
            this.usrCtrl.updateActiveUser(UserManagement.getUserById(this.usrCtrl.getActiveUser().getId()));
        }
        loadLowStockItems();
        
        if (this.activeUser.type.equalsIgnoreCase("staff")) {
            resolveButton.setVisible(true);
            resolveButton.setEnabled(true);
        } else {
            resolveButton.setVisible(false);
            resolveButton.setEnabled(false);
        }
    }
    
    public void loadLowStockItems() {
        DefaultTableModel model = (DefaultTableModel) lowStockTable.getModel();
        model.setRowCount(0);
        ArrayList<LinkedHashMap<String, String>> lowStockItems = PPEManagement.getLowStockItems();
        for (LinkedHashMap<String, String> item: lowStockItems) {
            PPEItem ppeItem = PPEManagement.getPPEItemByCode(item.get("itemCode"));
            String[] itemData = {ppeItem.getCode(), ppeItem.getName(), String.valueOf(ppeItem.getQuantity()), item.get("resolutionStatus"), item.get("staffInvolved")};
            model.addRow(itemData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lowStockNum = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowStockTable = new javax.swing.JTable();
        resolveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(770, 642));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 642));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Low Stock Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lowStockNum.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lowStockNum.setForeground(new java.awt.Color(204, 0, 0));
        lowStockNum.setText("5");
        jPanel1.add(lowStockNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 30, 40, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Below are the items with stock quantities below the threshold of 25 boxes. Please review and take appropriate actions.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        jTextArea1.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 660, 80));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        lowStockTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lowStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM CODE", "ITEM NAME", "AVAILABLE STOCK", "STATUS", "STAFF INVOLVED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lowStockTable.setAutoscrolls(false);
        lowStockTable.setEditingRow(0);
        lowStockTable.setGridColor(new java.awt.Color(255, 255, 255));
        lowStockTable.setIntercellSpacing(new java.awt.Dimension(20, 5));
        lowStockTable.setRowHeight(40);
        jScrollPane1.setViewportView(lowStockTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 660, 330));

        resolveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resolveButton.setText("Resolve");
        resolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resolveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveButtonActionPerformed
        int selectedRow = lowStockTable.getSelectedRow();
        if (selectedRow != -1) {
            String option = JOptionPane.showInputDialog(this, "Resolution Status: ", "Resolve Low Stock Items", JOptionPane.QUESTION_MESSAGE);
            if (option != null) {
                String itemCode = lowStockTable.getValueAt(selectedRow, 0).toString();
                PPEItem item = PPEManagement.getPPEItemByCode(itemCode);
                String status = option;
                LinkedHashMap<String, String> msg = this.usrCtrl.getPPEController().updateLowStockItemStatus(itemCode, status, this.usrCtrl.getActiveUser().getId());
                if (msg.get("success") != null) {
                    JOptionPane.showMessageDialog(this, String.format("PPE Item ('%s', '%s') low stock resolution status is updated!", item.getCode(), item.getName()));
                    loadLowStockItems();
                } else {
                    JOptionPane.showMessageDialog(this, String.format("Fail to resolve low stock PPE Item {'%s' - '%s'} :(\n", itemCode, item.getName()) + msg.get("msg"), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("User canceled input.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row first");
        }
    }//GEN-LAST:event_resolveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lowStockNum;
    private javax.swing.JTable lowStockTable;
    private javax.swing.JButton resolveButton;
    // End of variables declaration//GEN-END:variables
}
