/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycom.gui.manager;

import mycom.controllers.UserController;
import mycom.gui.LoginGUI;
import mycom.gui.admin.*;
import mycom.models.User;
import mycom.services.UserManagement;

/**
 *
 * @author sheaw
 */
public class ManagerNavigation extends javax.swing.JFrame {
    User manager;
    UserController usrCtrl;
    /**
     * Creates new form AdminDashboard
     */
    public ManagerNavigation(UserController usrCtrl) {
        initComponents();
        this.manager = usrCtrl.getActiveUser();
        this.usrCtrl = usrCtrl;
        ManagerDashboard dashboard = new ManagerDashboard(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
        
        if (this.usrCtrl.getActiveUser().type.equalsIgnoreCase("super admin")) {
            this.usrCtrl.updateActiveUser(UserManagement.getSuperAdmin());
        } else {
            this.usrCtrl.updateActiveUser(UserManagement.getUserById(this.usrCtrl.getActiveUser().getId()));
        }
        
        if (this.usrCtrl.getUserServices().getCRUDManager() || this.usrCtrl.getUserServices().getCRUDStaff()) {
            managerUserManagementButton.setVisible(true);
            managerUserManagementButton.setEnabled(true);
        } else {
            managerUserManagementButton.setVisible(false);
            managerUserManagementButton.setEnabled(false);
        }
        if (this.usrCtrl.getUserServices().getInitializeInventory() || this.usrCtrl.getUserServices().getResetInventory() || this.usrCtrl.getUserServices().getResetSystem()) {
            managerSystemManagementButton.setVisible(true);
            managerSystemManagementButton.setEnabled(true);
        } else {
            managerSystemManagementButton.setVisible(false);
            managerSystemManagementButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        welcomeManagerText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        managerUserManagementButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        managerGenerateReportButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        managerSystemManagementButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        managerLowStockRecordsButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        managerViewInventoryButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        managerLogoutButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        managerDashboardButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1120, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 730));

        topBar.setBackground(new java.awt.Color(144, 174, 223));
        topBar.setPreferredSize(new java.awt.Dimension(1120, 88));
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/icon.png"))); // NOI18N
        jLabel1.setText("PPE Inventory Management System");
        jLabel1.setIconTextGap(40);
        topBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        sideBar.setBackground(new java.awt.Color(52, 52, 58));
        sideBar.setPreferredSize(new java.awt.Dimension(350, 642));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeManagerText.setBorder(null);
        welcomeManagerText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        welcomeManagerText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(52, 52, 58));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome, \nManager");
        jTextArea1.setWrapStyleWord(true);
        welcomeManagerText.setViewportView(jTextArea1);

        sideBar.add(welcomeManagerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycom/gui/images/welcome_manager.png"))); // NOI18N
        sideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -1, 330, 250));

        managerUserManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerUserManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerUserManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerUserManagementButtonMouseClicked(evt);
            }
        });
        managerUserManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User Management");
        jLabel8.setFocusable(false);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerUserManagementButton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerUserManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 350, 40));

        managerGenerateReportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerGenerateReportButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerGenerateReportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerGenerateReportButtonMouseClicked(evt);
            }
        });
        managerGenerateReportButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Generate Report");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerGenerateReportButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerGenerateReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 350, 40));

        managerSystemManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerSystemManagementButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerSystemManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerSystemManagementButtonMouseClicked(evt);
            }
        });
        managerSystemManagementButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("System Management");
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerSystemManagementButton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerSystemManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 350, 40));

        managerLowStockRecordsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerLowStockRecordsButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerLowStockRecordsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerLowStockRecordsButtonMouseClicked(evt);
            }
        });
        managerLowStockRecordsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Low Stock Records");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerLowStockRecordsButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerLowStockRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 350, 40));

        managerViewInventoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerViewInventoryButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerViewInventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerViewInventoryButtonMouseClicked(evt);
            }
        });
        managerViewInventoryButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Inventory");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerViewInventoryButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerViewInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 350, 40));

        managerLogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerLogoutButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerLogoutButtonMouseClicked(evt);
            }
        });
        managerLogoutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Logout");
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerLogoutButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 350, 40));

        managerDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerDashboardButton.setPreferredSize(new java.awt.Dimension(350, 40));
        managerDashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerDashboardButtonMouseClicked(evt);
            }
        });
        managerDashboardButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managerDashboardButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, -1));

        sideBar.add(managerDashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 40));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(770, 642));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void managerDashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerDashboardButtonMouseClicked
        ManagerDashboard dashboard = new ManagerDashboard(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dashboard).setVisible(true);
    }//GEN-LAST:event_managerDashboardButtonMouseClicked

    private void managerViewInventoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerViewInventoryButtonMouseClicked
        ManagerViewInventory viewInventory = new ManagerViewInventory(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(viewInventory).setVisible(true);
    }//GEN-LAST:event_managerViewInventoryButtonMouseClicked

    private void managerLowStockRecordsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerLowStockRecordsButtonMouseClicked
        LowStockRecords lowStockRecords = new LowStockRecords(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(lowStockRecords).setVisible(true);
    }//GEN-LAST:event_managerLowStockRecordsButtonMouseClicked

    private void managerGenerateReportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerGenerateReportButtonMouseClicked
        ManagerGenerateReport generateReport = new ManagerGenerateReport(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(generateReport).setVisible(true);
    }//GEN-LAST:event_managerGenerateReportButtonMouseClicked

    private void managerUserManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerUserManagementButtonMouseClicked
//        ManagerUserManagement userManagement = new ManagerUserManagement();
//        jDesktopPane1.removeAll();
//        jDesktopPane1.add(userManagement).setVisible(true);
        UserManagementGUI userManagement = new UserManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(userManagement).setVisible(true);
    }//GEN-LAST:event_managerUserManagementButtonMouseClicked

    private void managerSystemManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerSystemManagementButtonMouseClicked
//        ManagerSystemManagement systemManagement = new ManagerSystemManagement();
//        jDesktopPane1.removeAll();
//        jDesktopPane1.add(systemManagement).setVisible(true);
        SystemManagementGUI systemManagement = new SystemManagementGUI(this.usrCtrl);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(systemManagement).setVisible(true);
    }//GEN-LAST:event_managerSystemManagementButtonMouseClicked

    private void managerLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerLogoutButtonMouseClicked
        dispose();
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.usrCtrl.userLogout(this.manager);
    }//GEN-LAST:event_managerLogoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManagerNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManagerNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManagerNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManagerNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManagerNavigation().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel managerDashboardButton;
    private javax.swing.JPanel managerGenerateReportButton;
    private javax.swing.JPanel managerLogoutButton;
    private javax.swing.JPanel managerLowStockRecordsButton;
    private javax.swing.JPanel managerSystemManagementButton;
    private javax.swing.JPanel managerUserManagementButton;
    private javax.swing.JPanel managerViewInventoryButton;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel topBar;
    private javax.swing.JScrollPane welcomeManagerText;
    // End of variables declaration//GEN-END:variables
}
